name: 'JLU autocheck bot'

on:
  schedule:
    - cron: '0 13 * * *'  # utc+8 21:00
    - cron: '0 23 * * *'  # utc+8 7:00

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Setup python'
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: 'Install dependencies'
        run: python -m pip install --upgrade requests lxml bs4 
      - name: 'Check'
        env:
          USERNAME: ${{ secrets.MY_USERNAME }}
          PASSWORD: ${{ secrets.MY_PASSWORD }}
        run: python main.py --user USERNAME --pwd PASSWORD
